import { useEffect } from "react";
import { SiteHeader, SiteFooter } from "./SiteChrome.jsx";

export function AboutPage() {
  useEffect(() => { document.title = "About us — CELCN"; }, []);
  return <><SiteHeader /><main className="about-page">
    <section className="about-intro section"><div><p className="kicker">About us</p><h1>Behind every bright beginning,<br />there are people who care.</h1><p>CELCN—the Canadian Early Learning &amp; Childcare Network—is being developed around a simple belief: supporting the people who care for children is part of supporting children themselves.</p></div><figure><img src="/assets/celcn-story.png" alt="An educator and a young child exploring a puzzle together in a daycare classroom" /></figure></section>
    <section className="about-purpose section"><p className="kicker">Our purpose</p><div><h2>Care is a shared responsibility.</h2><p>A child’s day is shaped by many people: family members, educators, centre leaders, and the wider community. Our ambition is to help those relationships feel more connected and better supported.</p><p>We’re bringing a community-minded approach to the practical side of early learning, with room for local knowledge, different perspectives, and the realities of running a childcare centre.</p></div></section>
    <section className="about-values section" aria-labelledby="values-title"><p className="kicker">What guides us</p><h2 id="values-title">People first. Purpose always.</h2><div className="about-value-grid"><article><span>01</span><h3>Listen before building.</h3><p>The experiences of families and early-learning professionals should help shape the decisions we make.</p></article><article><span>02</span><h3>Respect local context.</h3><p>Communities have different needs. We value approaches that leave space for local relationships and understanding.</p></article><article><span>03</span><h3>Make support practical.</h3><p>Our aim is to make everyday work clearer, so the people behind it can stay focused on meaningful care.</p></article></div></section>
    <section className="about-future section"><div><p className="kicker light">A network taking shape</p><h2>Help shape what comes next.</h2></div><div><p>CELCN’s network and platform are still developing. We welcome conversations with educators, centre operators, families, and potential partners who share an interest in stronger early-learning communities.</p><a className="button button-gold" href="/contact">Connect with us <span aria-hidden="true">↗</span></a></div></section>
  </main><SiteFooter /></>;
}
